### ISSUE TITLE
Ubuntu 16.04.3 LTS: ImportError: /tmp/_MEIV9rqI9/PIL._imaging.so

### ISSUE THREAD

**Issue by mickae1** [ciromattia/kcc#240]
I've take the last version of kcc source and after a success build with the command: 

sudo python3 setup.py build_binary

and a success install of the deb file, I got this error : 

Traceback (most recent call last):
  File "kcc.py", line 71, in <module>
  File "kindlecomicconverter/startup.py", line 29, in start
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "kindlecomicconverter/KCC_gui.py", line 36, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "kindlecomicconverter/comic2ebook.py", line 37, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "PIL/Image.py", line 56, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /tmp/_MEIV9rqI9/PIL._imaging.so: ELF load command address/offset not properly aligned

**Comment by AcidWeb** [comment]
Welcome in world of building pyton binary blobs. There is so many variables in this process I can't even guess what went wrong.

If for some reason you don't want use prebuild DEB i suggest to install KCC using PIP.

**Comment by mickae1** [comment]
It worked with : 
sudo python3 setup.py install

**Comment by AcidWeb** [comment]
Found the cause of problem - I will fix next binary release.
