### ISSUE TITLE
Release 5.4.3 dosen't work on Ubuntu 17.10

### ISSUE THREAD

**Issue by goldbird3** [ciromattia/kcc#251]
Installed Ubuntu 17.10 today (from scratch) and kcc won't start after installation. Worked fine with Ubuntu 17.04.
Console output is as follows:

```
xxx@xxx-ubuntu:~/Downloads$ kcc
Traceback (most recent call last):
  File "kcc.py", line 72, in <module>
  File "kindlecomicconverter/startup.py", line 29, in start
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "kindlecomicconverter/KCC_gui.py", line 27, in <module>
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
[3189] Failed to execute script kcc
xxx@xxx-ubuntu:~/Downloads$ 
```

**Comment by AcidWeb** [comment]
Woes of Linux binaries.

For now only "fix" I can provide is using PyPi version of KCC.

**Comment by AcidWeb** [comment]
Our binary pipeline is completely incompatible with library changes in 17.10.

DEBs are currently build on Ubuntu 14.04 and I can't make them generic enough to work on Ubuntu newer that 17.04.

For now I don't have time nor inclination to expand pipeline to provide proper matrix for Linux builds.

**Comment by AcidWeb** [comment]
Packages for 17.10 are out.
