### ISSUE TITLE
Permission denied: '/mnt/system/thumbnails'

### ISSUE THREAD

**Issue by lapwat** [ciromattia/kcc#338]
I have a strange error about permissions when generating a `mobi` file and running `kcc` without `sudo`.

```sh
Traceback (most recent call last):
  File "xxx/.virtualenvs/scan_scraper/lib/python3.8/site-packages/kindlecomicconverter/image.py", line 366, in saveToKindle
    self.image.save(os.path.join(kindle.path.split('documents')[0], 'system', 'thumbnails',
  File "xxx.virtualenvs/scan_scraper/lib/python3.8/site-packages/PIL/Image.py", line 2081, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: '/mnt/system/thumbnails/thumbnail_0b462e9c-062b-418c-8eca-f030043e214e_EBOK_portrait.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xxx/.virtualenvs/scan_scraper/lib/python3.8/site-packages/kindlecomicconverter/KCC_gui.py", line 402, in run
    comic2ebook.options.covers[outputPath.index(item)][0].saveToKindle(
  File "xxx/.virtualenvs/scan_scraper/lib/python3.8/site-packages/kindlecomicconverter/image.py", line 369, in saveToKindle
    raise RuntimeError('Failed to upload cover.')
RuntimeError: Failed to upload cover.
```

It does not prevent the generation of a valid `mobi` file. It just prevents the thumbnail to be uploaded because it is stored in a folder not accessible by kcc.

In which case do you want to upload the cover?
Do you need the Kindle to be mounted to try to upload the cover?
Isn't the cover stored inside the `mobi` file?

I will try to investigate...

**Comment by AcidWeb** [comment]
Cover upload is optional and it is uploaded if KCC detect mounted Kindle. Without it cover will be missing in few places as Kindle firmware don't use cover embedded in file.

It seems like something in your system is blocking access to mounted volumes.

**Comment by lapwat** [comment]
Yes, I mount my Kindle with `sudo`, so I assume kcc needs to be running in `sudo` to upload the thumbnail.
