### ISSUE TITLE
Python Script TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by HarveyB02** [ciromattia/kcc#410]
When running kcc-c2e.exe installed with pip, the following error occurs

`
Traceback (most recent call last):                                                                        File "C:\Users\harve\AppData\Roaming\Python\Python39\Scripts\kcc-c2e-script.py", line 33, in <module>     sys.exit(load_entry_point('KindleComicConverter==5.5.2', 'console_scripts', 'kcc-c2e')())             File "C:\Users\harve\AppData\Roaming\Python\Python39\site-packages\kindlecomicconverter\startup.py", line 46, in startC2E                                                                                         dependencyCheck(2)                                                                                    File "C:\Users\harve\AppData\Roaming\Python\Python39\site-packages\kindlecomicconverter\shared.py", line 121, in dependencyCheck                                                                                  if StrictVersion('1.2.1') > StrictVersion(slugifyVersion):                                            File "C:\Users\harve\AppData\Local\Programs\Python\Python39\lib\distutils\version.py", line 40, in __init__                                                                                                       self.parse(vstring)                                                                                   File "C:\Users\harve\AppData\Local\Programs\Python\Python39\lib\distutils\version.py", line 135, in parse                                                                                                         match = self.version_re.match(vstring)                                                              TypeError: expected string or bytes-like object
`

Any tips?
Windows 11
Python 3.9.9
pip 21.2.4

**Comment by darodi** [comment]
the problem seems related to your slugify version.
try that in the python command line, what is the result?

```python
from slugify import __version__ as slugifyVersion
print(slugifyVersion)
from distutils.version import StrictVersion
print(StrictVersion(slugifyVersion))
```

**Comment by HarveyB02** [comment]
@darodi
```py
>>> from slugify import __version__ as slugifyVersion
>>> print(slugifyVersion)
<module 'slugify.__version__' from 'C:\\Users\\harve\\AppData\\Roaming\\Python\\Python39\\site-packages\\slugify\\__version__.py'>
>>> from distutils.version import StrictVersion
>>> print(StrictVersion(slugifyVersion))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\harve\AppData\Local\Programs\Python\Python39\lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "C:\Users\harve\AppData\Local\Programs\Python\Python39\lib\distutils\version.py", line 135, in parse
    match = self.version_re.match(vstring)
TypeError: expected string or bytes-like object
```

**Comment by darodi** [comment]
you should have a result like that:

```
>>> from slugify import __version__ as slugifyVersion
>>> print(slugifyVersion)
2.0.1
```

try reinstalling slugify 

`pip install "python-slugify>=1.2.1,<3.0.0"`
then 
`pip install --user KindleComicConverter`

**Comment by HarveyB02** [comment]
That worked, thanks - missed the version in the dependencies
