### ISSUE TITLE
how to fix no such file or directory "file.mobi"

### ISSUE THREAD

**Issue by yogeshdcool** [ciromattia/kcc#423]
OS: Archlinux
version:tried latest from both aur and pypi

error:During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yogi/.local/lib/python3.10/site-packages/kindlecomicconverter/KCC_gui.py", line 381, in run
    self.workerOutput.append(comic2ebook.makeMOBIFix(
  File "/home/yogi/.local/lib/python3.10/site-packages/kindlecomicconverter/comic2ebook.py", line 1166, in makeMOBIFix
    move(mobiPath, mobiPath + '_toclean')
  File "/usr/lib/python3.10/shutil.py", line 833, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yogi/Downloads/berserk-2.mobi'

**Comment by darodi** [comment]
@yogeshdcool 

is the issue still present in v5.6.1 https://github.com/ciromattia/kcc/releases/tag/v5.6.1?

**Comment by darodi** [comment]
closing this.

pypi releases have been discontinued
please user AppImage, Flatpak, Docker or python sources instead.
