### ISSUE TITLE
pip based installation is not working

### ISSUE THREAD

**Issue by smaarn** [ciromattia/kcc#444]
While trying to use this interesting tool I stumbled a weird issue when installing using pip (I actually use an outdated mac os version so... not much choice here ;) ). Basically the kcc command line tool would fail starting. See below for details

## Reproduction path

- Install using pip
- Start kcc

Error being raised:
```
Traceback (most recent call last):
  File "/Users/antoine/Library/Python/3.8/bin/kcc", line 8, in <module>
    sys.exit(start())
  File "/Users/antoine/Library/Python/3.8/lib/python/site-packages/kindlecomicconverter/startup.py", line 28, in start
    dependencyCheck(3)
  File "/Users/antoine/Library/Python/3.8/lib/python/site-packages/kindlecomicconverter/shared.py", line 121, in dependencyCheck
    if StrictVersion('1.2.1') > StrictVersion(slugifyVersion):
  File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/version.py", line 54, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/version.py", line 155, in parse
    match = self.version_re.match(vstring)
TypeError: expected string or bytes-like object
```

**Comment by smaarn** [comment]
From what I gathered the dev environment is actually using a version range (>=1.2.1 <3.0.0) while the plain setup does not.

More specifically, the prod version is taking the latest version available. And starting from version 6 of `slugify`, the library actually provides with a `__version__` module which contains several information, including the `__version__` attribute.

**Comment by smaarn** [comment]
Duplicate of #410 

All apologies for inconvenience caused !
