### ISSUE TITLE
KeyError: 'KPW5' when adding specific profile

### ISSUE THREAD

**Issue by galloramiro** [ciromattia/kcc#490]
Hi guys, 

Im getting this error when I try to use a specific profile.
```bash
comic2ebook v5.5.2 - Written by Ciro Mattia Gonano and Pawel Jastrzebski.
Traceback (most recent call last):
  File "/home/eurekalabs/.local/bin/kcc-c2e", line 8, in <module>
    sys.exit(startC2E())
  File "/home/eurekalabs/.local/lib/python3.10/site-packages/kindlecomicconverter/startup.py", line 49, in startC2E
    sys.exit(main(sys.argv[1:]))
  File "/home/eurekalabs/.local/lib/python3.10/site-packages/kindlecomicconverter/comic2ebook.py", line 71, in main
    checkOptions()
  File "/home/eurekalabs/.local/lib/python3.10/site-packages/kindlecomicconverter/comic2ebook.py", line 1029, in checkOptions
    options.profileData = image.ProfileData.Profiles[options.profile]
KeyError: 'KPW5'

```

I did git fetch and pull and re build the project to se if I could get the 6.1 version but I still get the 5.2
Thanks

**Comment by galloramiro** [comment]
I fix it using the KPW, I get the values from [this file ](https://github.com/ciromattia/kcc/blob/master/kindlecomicconverter/comic2ebook.py#L944) if you want I can make a PR to update the profiles removing the not available. 
But I dont know if that would be right.

**Comment by galloramiro** [comment]
Found out the problem Im using the [PyPi version](https://pypi.org/project/KindleComicConverter/) and its outdated. 
Should I move to other ways to use the stand alone?

**Comment by galloramiro** [comment]
Its working, im using flatpak, forgot to update the issue. 
Thanks!

**Comment by galloramiro** [comment]
Its working, im using flatpak, forgot to update the issue. 
Thanks!
