### ISSUE TITLE
Flatpak version of KCC (5.6.4) can't be started

### ISSUE THREAD

**Issue by winstonma** [ciromattia/kcc#636]
**Describe the bug**

**To Reproduce**
Go to terminal, update KCC and I got the following result.
```bash
$ flatpak info io.github.ciromattia.kcc

Kindle Comic Converter - An app that allows you to transform your PNG, JPG,
GIF, CBZ, CBR and CB7 files into EPUB or MOBI format e-books

          ID: io.github.ciromattia.kcc
         Ref: app/io.github.ciromattia.kcc/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 5.6.4
     License: ISC
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 44.4 MB
     Runtime: org.kde.Platform/x86_64/5.15-23.08
         Sdk: org.kde.Sdk/x86_64/5.15-23.08

      Commit: 7b5fc1626564c3e4631c07f0b78ce2d263554e346f4936c30136ae5470e3ced3
      Parent: 199be7911bc102208f052391fbe3d1aad2749294195c6be440ba4ca17580cb5a
     Subject: Update v5.6.3.tar.gz to 5.6.4 (3a7442ea)
        Date: 2023-12-05 05:08:34 +0000

$ flatpak run io.github.ciromattia.kcc
Traceback (most recent call last):
  File "/app/bin/kcc", line 33, in <module>
    sys.exit(load_entry_point('KindleComicConverter==5.6.4', 'gui_scripts', 'kcc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/kindlecomicconverter/startup.py", line 29, in start
    from . import KCC_gui
  File "/app/lib/python3.11/site-packages/kindlecomicconverter/KCC_gui.py", line 39, in <module>
    from . import comic2ebook
  File "/app/lib/python3.11/site-packages/kindlecomicconverter/comic2ebook.py", line 34, in <module>
    from natsort import natsorted
ModuleNotFoundError: No module named 'natsort'
```

**Expected behavior**

**Screenshots**
Add a screenshot of your KCC settings.

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**

**Comment by axu2** [comment]
@catsout I assume this file needs to be updated to add the `natsort` dependency?

**Comment by winstonma** [comment]
@axu2  Yep it is working now

Thanks

**Comment by axu2** [comment]
Thank you @catsout !
