### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by maximzero0910** [ciromattia/kcc#759]
When I try to install it it keeps saying this:

Traceback (most recent call last):
  File "kcc.py", line 76, in <module>
  File "kindlecomicconverter\startup.py", line 29, in start
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "kindlecomicconverter\KCC_gui.py", line 29, in <module>
ImportError: DLL load failed while importing QtGui: A dynamic link library (DLL) initialization routine failed.
 
I reinstalled all of Python, tried running it as an admin, and disabled real-time protection to make sure, but nothing worked.

All help is appreciated!

**Comment by axu2** [comment]
@maximzero0910 what os are you using? Windows 10?

**Comment by maximzero0910** [comment]
> @maximzero0910 what os are you using? Windows 10?

win 11

**Comment by axu2** [comment]
Try. 

1) restart PC and try again. 

Still doesn't work?

Uninstall python and repeat step 1. @maximzero0910

**Comment by maximzero0910** [comment]
> Try.
> 
> 1. restart PC and try again.
> 
> Still doesn't work?
> 
> Uninstall python and repeat step 1. @maximzero0910
> 
> Are you running the prebuilt exe or the python code directly?

im using the prebulit version.

**Comment by axu2** [comment]
@axu2 also lmk if 5.6.5 or any newer versions work.

**Comment by axu2** [comment]
also lmk if kcc 5.6.5 or any newer versions work. @maximzero0910

**Comment by axu2** [comment]
@maximzero0910 

You can try running the python code directly, not pre-built. https://github.com/ciromattia/kcc?tab=readme-ov-file#install-from-source

It would probably give a better error message.

**Comment by axu2** [comment]
@maximzero0910 

I'll try building with newer python versions, can you test these prebuilt ones?

https://github.com/axu2/kcc/releases/tag/v7.1.2-py3.12
https://github.com/axu2/kcc/releases/tag/v7.1.2-py3.13

**Comment by axu2** [comment]
@maximzero0910 kcc 7.3.1 is built different, does it help?

**Comment by axu2** [comment]
Maybe switching from `pyinstaller` to `pyside6-deploy` would fix this.

**Comment by axu2** [comment]
Small chance the win7 build works `kcc_win7.exe`

**Comment by axu2** [comment]
Read somewhere that installing the python version that kcc uses may fix the problem: https://www.python.org/downloads/release/python-3119/
